### ISSUE TITLE
Add more tests

### ISSUE THREAD

**Issue by felipeZ** [SCM-NV/qmflows#160]
TODO:
* [x] Tests for ADF parser
* [x] Tests the generic parsers
* [x] Mock ADF
* [x] Mock ORCA
* [x] Mock CP2K

**Comment by BvB93** [comment]
It also seems like the old DFTB module (as implemented in ADF) is now deprecated; it's only accessible since 2019 or so via the AMS driver.

**Comment by BvB93** [comment]
Speaking of tests, might it be an idea to enable the tests for Python 3.8?

**Comment by felipeZ** [comment]
> Speaking of tests, might it be an idea to enable the tests for Python 3.8?

Let's do so :+1:

**Comment by BvB93** [comment]
Allright, shall I push the change or do you want to do it?

**Comment by felipeZ** [comment]
fixed by #163
