### ISSUE TITLE
Replace `init()` with `InitRestart`?

### ISSUE THREAD

**Issue by BvB93** [SCM-NV/qmflows#197]
So some time ago I added the [`qmflows.utils.init_restart()`](https://github.com/SCM-NV/qmflows/blob/61c64517fc676888a7eba3b7e12ec9b1bd10fdc6/src/qmflows/utils.py#L121) function and matching [`qmflows.utils.InitRestart`](https://github.com/SCM-NV/qmflows/blob/61c64517fc676888a7eba3b7e12ec9b1bd10fdc6/src/qmflows/utils.py#L169) context manager in order to *not* create a new directory every time a set of PLAMS jobs is initialized.
I was wondering, @felipeZ how would you feel about making this the default for [`qmflows.run()`](https://github.com/SCM-NV/qmflows/blob/61c64517fc676888a7eba3b7e12ec9b1bd10fdc6/src/qmflows/packages/packages.py#L542)? This would also allow for, _e.g._, the moving of the `cache.db` file to the, now persistent, PLAMS workdir (rather then just floating around in whatever happens to be the submission directory).

Examples
----------
``` python
def run(...) -> Result:
    with RestartInit(path=path, folder=folder):
        plams.config.log.stdout = 0

        if runner is None:
            return call_default(job, kwargs.get('n_processes', 1), kwargs.get('always_cache', True))
        else:
            raise ValueError(f"Don't know runner: {runner}")
```

**Comment by felipeZ** [comment]
@BvB93  I am all in for that!

**Comment by BvB93** [comment]
Alright, then I'll create a bit later.
