### ISSUE TITLE
Run cp2k with srun

### ISSUE THREAD

**Issue by felipeZ** [SCM-NV/qmflows#204]
## Problem
For some hardware `srun` is a better choice than `mpirun` therefore, I would be great if we first to use `srun` if available, otherwise use `mpirun`

**Comment by BvB93** [comment]
See https://github.com/SCM-NV/PLAMS/pull/90 for implementation details

**Comment by felipeZ** [comment]
fix by [SCM-NV/PLAMS#90](https://github.com/SCM-NV/PLAMS/pull/90)
