### ISSUE TITLE
Run tests in MaCOS and deactivate travis

### ISSUE THREAD

**Issue by felipeZ** [SCM-NV/qmflows#205]
TODO:
* [x] Run Tests on MacOS
* [x] Deactivate Travis

**Comment by BvB93** [comment]
By the way, what was the reason for dropping python 3.6 support again?

**Comment by felipeZ** [comment]
> By the way, what was the reason for dropping python 3.6 support again?
I have a terrible memory, I am not sure if there was an issue at all. We can add it and see if it works :)

**Comment by BvB93** [comment]
Found it, it seems to have been changed because of a noodles version bump (https://github.com/SCM-NV/qmflows/pull/130).
Something related to noodles' bump to python `>= 3.7` because of https://github.com/NLeSC/noodles/issues/80.

**Comment by BvB93** [comment]
Eh, let's just give python 3.6 a shot and see if it feels.
