### ISSUE TITLE
setup of calling packages

### ISSUE THREAD

**Issue by houzf** [SCM-NV/qmflows#208]
**Is your feature request related to a problem? Please describe.**
The note for the setup of calling pacakges is too simple to be followed, particullary for the case that a user isn't able to use "load module superAwesomeQuantumPackage/3.1421"
"https://qmflows.readthedocs.io/en/stable/interactive_tutorial.html#The-basics:-calling-packages"

**Describe the solution you'd like**
How to set up the path of exectuable file (CP2K, DFTB, and so on) so that it can be passed to qmflows?  For example, the ASE pacakge uses the environment variables to set up the different calculators. 

Could the developer provide an example (or template file) for the setup of calling different calculators?

**Comment by felipeZ** [comment]
@houzf  qmpackage assumes that the binaries are installed and available. It would try to search for the binaries as follows:
* For ADF and DFTB the library is going to use the [ADFBIN](https://www.scm.com/doc/ADF/index.html) environment variable, so you can setup that variable.
* For CP2K the default binary is `cp2k.popt` which the library will try to execute using `mpirun` or `srun` if possible. You can also, provide other executables like:
```python
from qmflows import Settings
s = Settings()
settings.specific.cp2k.executable = "cp2k.psmp"
```
You can specify as executable any of the *cp2k* binaries: `{"sdbg", "sopt", "ssmp", "pdbg", "popt", "psmp"}`

* For ORCA the binary name `orca` is used.

**Comment by houzf** [comment]
Thank you very much for your reply. 

Just now I figure out the setup of cp2k by many trials. Here is an example of the script file. The  CP2K 7.1-version was used. 

-----------------------------
from qmflows import Settings
from scm.plams import Molecule
from qmflows import cp2k,run, templates
penta = Settings()

penta.input.force_eval.dft.basis_set_file_name = "/home/hou/soft/cp2k/data/BASIS_MOLOPT"
penta.input.force_eval.dft.potential_file_name = "/home/hou/soft/cp2k/data/POTENTIAL"
penta.input.force_eval.dft.mgrid.cutoff = 400
penta.input.force_eval.dft.mgrid.ngrids = 4
penta.input.force_eval.dft.poisson = Settings()
penta.input.force_eval.dft.localize._h = "T"

penta.executable='/home/hou/soft/cp2k/tools/toolchain/install/openmpi-4.0.2/bin/mpirun -np 16 /home/hou/soft/cp2k/exe/local/cp2k.psmp'
penta.input.force_eval.method = "QS"
penta.input.force_eval.dft.qs.method = "GPW"
penta.input.force_eval.dft.scf.eps_scf = 1e-6
penta.input.force_eval.dft.scf.max_scf = 200
penta.input.force_eval.dft.xc.xc_functional.PBE.PARAMETRIZATION ='ORIG'

penta.input.force_eval.subsys.cell.A = '16.11886919 0.07814137 -0.697284243'
penta.input.force_eval.subsys.cell.B = '-0.215317662  4.389405268  1.408951791'
penta.input.force_eval.subsys.cell.C = '-0.216126961 1.732808365 9.74896108'
penta.input.force_eval.subsys.cell.periodic = 'XYZ'
penta.input.force_eval.subsys.kind.C.basis_set = "DZVP-MOLOPT-SR-GTH-Q4"
penta.input.force_eval.subsys.kind.C.potential = "GTH-PBE-Q4"
penta.input.force_eval.subsys.kind.H.basis_set = "DZVP-MOLOPT-SR-GTH-Q1"
penta.input.force_eval.subsys.kind.H.potential = "GTH-PBE-q1"

molecule=Molecule("./ethylene.xyz")
job = cp2k(templates.singlepoint.overlay(penta),molecule, job_name='cp2k')
results = run(job,folder='.')
print(results.energy)
-----------------------------------
