### ISSUE TITLE
ADF template default cause problems

### ISSUE THREAD

**Issue by felipeZ** [SCM-NV/qmflows#227]
## The problem
With the current [ADF template](https://github.com/SCM-NV/qmflows/blob/5754a88fec66ad961542cdff660ec2167e16da2a/src/qmflows/templates/templates.py#L10-L18) If the user passes an hybrid functional,  the `lda` keyword is not overwrite causing the generation of an invalid input.

## Solution
Remove the `xc` section from the ADF template.

**Comment by BvB93** [comment]
I think ADF will still default to LDA if no XC is specified whatsoever.
So in that sense this change shouldn't alter the level of theory.

**Comment by felipeZ** [comment]
> I think ADF will still default to LDA if no XC is specified whatsoever.
> So in that sense this change shouldn't alter the level of theory.

That is good to know, so we don't break people's code

**Comment by BvB93** [comment]
Resolved by https://github.com/SCM-NV/qmflows/pull/228.
