### ISSUE TITLE
Querying for properties

### ISSUE THREAD

**Issue by sgu800** [SCM-NV/qmflows#48]
Dear Johan and Lars,

I was running workflow for TS search with DFTB frequencies(test1_withDFTBfreq.py) and it was successful with results(slurm-2471538.out).

I made a small modification in the workflow that I removed DFTB frequency calculation in the middle of workflow(test1_withoutDFTBfreq.py).

I ran second script in the same folder of previous script. First few steps in the both workflows are similar and the results are retrieved from cashe.json from previous run and remaining jobs were run and the results were saved into new plams folder. 

When I try to print table in the second workflow, it seems to be that it can't find results from first steps because the results are living in first plams folder.

I believe noodles thinks these as two different workflows irrespective of some common jobs. Is there any way to copy the retrieved information from cashe.json to new plams folder so that all the results from new workflows stays together. or am I missing something?

Could one of you please help me to solve these issue?

Kind regards,
Satesh

**Comment by ridderl** [comment]
Normally noodles should have no problem in getting results from different folders. Could you please send the modified script?

**Comment by jhidding** [comment]
I'll work on creating a configuration file where you can set the cache file location manually. Meanwhile you can set it yourself by editing packages.py, where you also set your account info for the Xenon runner.
