### ISSUE TITLE
Where are examples ?

### ISSUE THREAD

**Issue by miroi** [SCM-NV/qmflows#86]
Where are examples ?

https://github.com/SCM-NV/qmworks/tree/develop/examples

Page Not found...

**Comment by felipeZ** [comment]
Here are the tests using Dirac:
https://github.com/SCM-NV/qmworks/tree/master/test/test_using_plams/test_dirac
And here the examples of other packages:
https://github.com/SCM-NV/qmworks/tree/master/src/qmworks/examples
Also in this other folder are the tests that we used for all the packages:
https://github.com/SCM-NV/qmworks/tree/master/test/test_using_plams

**Comment by miroi** [comment]
Also, I would like to ask you how to insert DIRAC "pam" script path into plams/qmworks structures so that I don't have to keep it in $PATH.

**Comment by felipeZ** [comment]
you can do the following in your script
```python
import sys
# This is the path to the folder containing pam without including pam
pam_path="Path/to/folder/containing/pam"
sys.path.append(pam) 
```

**Comment by miroi** [comment]
Well,

still can not find pam script:
~~~
# take care of pam script :
import sys
# This is the path to the folder containing pam without including pam
pam_path="/u/milias/Work/qch/software/dirac/trunk/build_intelmkl_i8_xh"
sys.path.append(pam_path)
.
.
~~~
pam is in the directory ...
~~~
milias@lxir127.gsi.de:~/Work/qch/software/My_scripts/local_runs/gsi_de/lxir_nodes/dirac/python_scripting/plams_qmworks/.ls /u/milias/Work/qch/software/dirac/trunk/build_intelmkl_i8_xh/pam 
/u/milias/Work/qch/software/dirac/trunk/build_intelmkl_i8_xh/pam*
~~~

**Comment by miroi** [comment]
Isn't there a direct insertion of pam PATH as a library parameter ?

**Comment by miroi** [comment]
Finally I master working version, https://github.com/miroi/My_scripts/blob/master/local_runs/gsi_de/lxir_nodes/dirac/python_scripting/plams_qmworks/plams_run.py

But I need more functionalities: I want to run finite field RelCC calculations (z,x,y orientation of molecules) and interpolate extracted CCSD(T) energies as polynomial (numpy library?). From polynomial coefficients obtain the second derivatives - polarizabilities. Would it be please possible to run such job ?

**Comment by felipeZ** [comment]
You can use all the functionality of Python inside `Plams` or `QMWorks`. Actually I used a mixture of `Numpy`, `Pandas`, `Scipy`, `Cython`, etc. to perform further numerical computations.
In QMWorks for instance you can create an script then submitted with `sbatch` to slurm and QMWorks figure out the dependencies of all the jobs and run then in the corresponding order inside the node(s) that you requested from `SLURM`

**Comment by miroi** [comment]
The barrier to learn this 'pythonization' with all these Python libraries is too high.  The help lies in many different working examples/tutorials, so that the average user can try them step-by-step.

**Comment by felipeZ** [comment]
I agree, you probably will find the the [QMWorks](http://scm-nv.github.io/qmworks/) and [PLAMS](https://www.scm.com/doc/Tutorials/Scripting/Scripting.html) tutorials helpful.
