### ISSUE TITLE
Molkit module has been moved to Plams

### ISSUE THREAD

**Issue by felipeZ** [SCM-NV/qmflows#99]
the [molkit](https://github.com/SCM-NV/PLAMS/blob/master/interfaces/molecule/rdkit.py) Module has been moved to [plams](https://github.com/SCM-NV/PLAMS).

For backward compatibility it can be import as 
```
import scm.plams.interfaces.molecule.rdkit as molkit
```

**Comment by BvB93** [comment]
I'll move the new addition to plams once i've access
